# Generated by Django 3.0.2 on 2020-02-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200121_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkt', models.IntegerField()),
            ],
        ),
    ]
