# Generated by Django 3.0.2 on 2020-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_punkty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punkty',
            name='pkt',
            field=models.IntegerField(default=0),
        ),
    ]
